# Generated by Django 4.2.1 on 2023-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='image',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
